### ISSUE TITLE
Problems with two code login forms inserted in my website

### ISSUE THREAD

**Issue by sperlari** [vojtasvoboda/oc-codelogin-plugin#5]
Hi,
thanks for code login, It's a very useful plugin.

I need to create two different secret areas, each one with its Code Login form with a specific password.  
I needed a plugin that classified users by role, so, for example, if a password correspond with a "editor" role, this user could see a specific secret area.
To classified users by role I found Hierarchic Roles Plugin. 

Now I have different problems. 
1. If a user inserts a wrong password in the form A, Code Login plugin redirects him to the other Code Login form page (B).
2. Sometimes with the password A I can access to the secret content B instead of A.

Thanks in advance!

**Comment by vojtasvoboda** [comment]
Hi @spexy90, it's hard to say when I can't see your code :-( Can you put your code somewhere public? Maybe as a gist?

Do you have both code login form inserted to the one page?

This plugin allows you only to login with a password. It doesn't manage any permissions - you have to use it with combination with other plugins or custom functions.
