### ISSUE TITLE
What about wrong codes?

### ISSUE THREAD

**Issue by wmunguiam** [vojtasvoboda/oc-codelogin-plugin#6]
Hi! Interesting plugin!
Tested and works well but not sure about "Wrong code" event.
I only receive: 
Error
We're sorry, but an unhandled error occurred. Please see the details below.
Wrong code!
/var/www/html/usi/plugins/vojtasvoboda/codelogin/components/CodeLogin.php line 95
        /*
         * Find user by password
         */
        $users = new UserRepository();
        $userToLog = $users->getUserByPassword(array_get($data, 'code'));
        if ($userToLog === null) {
            $exception = new ValidationException([trans('vojtasvoboda.codelogin::lang.form.wrong_code')]);
            throw $exception;
        }
  
        /*
         * Authenticate user
         */

Do I have to work in "exception" condition? Or this is itegrated in plugin's components?

**Comment by vojtasvoboda** [comment]
Hi. This exception is automatically handled by October AJAX framework, so be sure you have `framework` and `framework extras` directive included in your layout. For more see Readme, chapter 1.

**Comment by wmunguiam** [comment]
:S 

Strange behaviour....

I checked directives and they are listed:

...

<script type="text/javascript" src="{{ 'assets/js/html5shiv.js'|theme }}"></script>
<script type="text/javascript" src="{{ 'assets/js/respond.min.js'|theme }}"></script>
<script type="text/javascript" src="{{ 'assets/js/jquery.js'|theme }}"></script>
<script type="text/javascript" src="{{ 'assets/js/bootstrap.min.js'|theme }}"></script>
<script type="text/javascript" src="{{ 'assets/js/jquery.prettyPhoto.js'|theme }}"></script>
<script type="text/javascript" src="{{ 'assets/js/jquery.isotope.min.js'|theme }}"></script>
<script type="text/javascript" src="{{ 'assets/js/main.js'|theme }}"></script>
<script type="text/javascript" src="{{ 'assets/js/wow.min.js'|theme }}"></script>
{% component 'session' %}
{% framework %}
{% framework extras %}
{% scripts %}           
         
</body>
</html>

October version: system Build 414,

**Comment by vojtasvoboda** [comment]
Wow, that is strange. There has to be some changes in Ajax framework. I made a fix, can you please test it?

https://github.com/vojtasvoboda/oc-codelogin-plugin/commit/bb8c97e7dd9bdc0fff0b3051b17895bb78100856

Thanks a lot for reporting issue.

**Comment by wmunguiam** [comment]
Same behaviour:

Edited file with line sent:
/var/www/html/sistemas/plugins/vojtasvoboda/codelogin/components/codelogin/default.htm

When I go to protected Page, it redirects to Login Page 
If I put rigth Code, Protected page is shown 
If I put a wrong Code, Exeption error Page is shown (attached)  :(
![codeplugin](https://cloud.githubusercontent.com/assets/10436761/25259240/97e7cd44-260a-11e7-936f-99c6c1eb5375.png)

**Comment by vojtasvoboda** [comment]
Sorry for the long delay. I found the problem and make new version 1.0.5 (now ready at the Market).

I've tested it on fresh CMS installation and everything works well with right login and also with bad one.

Could you please test it? Thank a lot.
