### ISSUE TITLE
Always get WRONG CODE

### ISSUE THREAD

**Issue by PappoYT** [vojtasvoboda/oc-codelogin-plugin#8]
I follow your guide to install plugin.
As described in point 4 I created a new user with a password. Then I manual activated user.
If I try the password in the code login form I always get the following error: `Wrong code!`.
![form](https://user-images.githubusercontent.com/74958346/115010943-53a8c680-9eae-11eb-8dba-79fc5ecc03bd.PNG)
![utente](https://user-images.githubusercontent.com/74958346/115010946-54415d00-9eae-11eb-9688-eb0da33bfe97.PNG)

**Comment by PappoYT** [comment]
Any help please?!

**Comment by vojtasvoboda** [comment]
Try to use username same as email, so username set to `yyy@gmail.com`. Or just go to the Settings > Users > Users management and set e-mail as login attribute.
